### ISSUE TITLE
warning提示问题

### ISSUE THREAD

**Issue by wanghuatao** [topameng/CsToLua#8]
Create not wrap ulua type:UnityEditor.Animations.AnimatorController, UnityEditor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

AnimatorController应该是在UnityEngine命名空间,ulua搞错了?

**Comment by topameng** [comment]
没有导出AnimatorController, 走的反射调用就会有这个警告。看下FAQ

**Comment by wanghuatao** [comment]
命名空间提示有问题,AnimatorController是在UnityEngine下,提示的是在UnityEditor
